name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.12.1, 20.0.0]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify backend directory exists
        run: |
          if [ ! -d "./backend" ]; then
            echo "Error: ./backend directory does not exist."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run backend unit tests
        run: npm test
        working-directory: ./backend

